name: 'Extract JIRA issues from history'
description: 'Extract JIRA issues e.g. ABC-123'
inputs:
  token:
    description: 'the git token'
    required: true
  jiraToken:
    description: 'JIRA api key'
    required: true
  pullRequestNumber:
    description: 'The PR number'
    required: false
    default: ''
  jiraUsername:
    description: 'The jira username *@myposter.de'
    required: true
  isPr:
    description: 'Is pr closed? Or get commits from develop -> master?'
    required: false
    default: false
  latestTag:
    description: 'if set, get diff between latest tag and head'
    required: false
    default: 'false'

outputs:
  issues:
    description: 'The issues as links'
runs:
  using: 'node16'
  main: 'dist/index.js'
