name: 'Extract JIRA issues from history'
description: 'Extract JIRA issues e.g. ABC-123'
inputs:
  token:
    description: 'the git token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
